### commit and push those values in !
substitutions:
  _TAG: v2.0.3
  _PATCHES: "bos-deep-mind-logging-v2.0.3-v10.0.patch bos-deep-mind-v2.0.3-v10.0.patch"

steps:
- id: docker-build-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/boscore-bos-full:${_TAG}-dm',
    '-t', 'gcr.io/${PROJECT_ID}/boscore-bos-full:${_TAG}-${SHORT_SHA}-dm',
    '-f', 'bos-full.dockerfile',
    '--cache-from', 'gcr.io/${PROJECT_ID}/boscore-bos-full:${_TAG}-dm',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]
# FIXME: Disabled for now as BOS is not booting yet
# - id: dm-tests
#   name: gcr.io/${PROJECT_ID}/boscore-bos-full:${_TAG}-${SHORT_SHA}-dm
#   dir: /workspace/dm/compare
#   args: [
#     './run.sh', '/opt/eos/bin/nodeos'
#   ]
- id: docker-build-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/boscore-bos-prod:${_TAG}-dm',
    '-t', 'gcr.io/${PROJECT_ID}/boscore-bos-prod:${_TAG}-${SHORT_SHA}-dm',
    '--build-arg', 'BOS_FULL_TAG=${_TAG}-${SHORT_SHA}-dm',
    '-f', 'bos-prod.dockerfile',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/boscore-bos-full:${_TAG}-dm
- gcr.io/$PROJECT_ID/boscore-bos-full:${_TAG}-${SHORT_SHA}-dm
- gcr.io/$PROJECT_ID/boscore-bos-prod:${_TAG}-${SHORT_SHA}-dm

timeout: 1h
