### commit and push those values in !
substitutions:
  _TAG: v1.6.1
    # check appropriate builder tag in https://hub.docker.com/r/eosio/builder/tags
  _BUILDER_TAG: v1.5.2
  _PATCHES: "deep-mind-v1.6.1-v8.3.patch deep-mind-logging-v1.6.1-v8.3.patch"

steps:
- id: docker-build-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind',
    '-f', 'Dockerfile-nodeos-full',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'BLDTAG=${_BUILDER_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]
- id: deep-mind-tests
  name: gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}
  dir: /workspace/deep-mind/compare
  args: [
    './run.sh', '/opt/eos/bin/nodeos'
  ]
- id: docker-build-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-prod:${_TAG}-deep-mind-${SHORT_SHA}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-prod:${_TAG}-deep-mind',
    '--build-arg', 'NODEOS_FULL_TAG=${_TAG}-deep-mind-${SHORT_SHA}',
    '-f', 'Dockerfile-nodeos-prod',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-nodeos-full:${_TAG}-deep-mind
- gcr.io/$PROJECT_ID/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}
- gcr.io/$PROJECT_ID/eosio-nodeos-prod:${_TAG}-deep-mind-${SHORT_SHA}

