substitutions:
  _TAG: v2.0.0
  _PULL_TAG: v2.0.0-rc3

steps:
- id: docker-eosio-buildenv
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-buildenv:${_TAG}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-buildenv:${_TAG}-${SHORT_SHA}',
    '-f', 'Dockerfile-eosio-buildenv',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-buildenv:${_TAG}',
    '--build-arg', 'SRCTAG=${_PULL_TAG}',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-buildenv:${_TAG}
- gcr.io/$PROJECT_ID/eosio-buildenv:${_TAG}-${SHORT_SHA}

timeout: 2h
