### commit and push those values in !
substitutions:
  _TAG: v1.8.5
  # Check available images with `gcloud container images list-tags gcr.io/eoscanada-shared-services/eosio-buildenv`
  _EOSIO_BUILDENV_TAG: v1.8.1

steps:
- id: docker-eos-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}-jungle2-fix',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}-${SHORT_SHA}-jungle2-fix',
    '-f', 'Dockerfile-eos-full',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}-jungle2-fix',
    '--build-arg', 'EOSIO_BUILDENV_TAG=${_EOSIO_BUILDENV_TAG}',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]
- id: docker-eos-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-prod:${_TAG}-jungle2-fix',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-prod:${_TAG}-${SHORT_SHA}-jungle2-fix',
    '--build-arg', 'EOS_FULL_TAG=${_TAG}-${SHORT_SHA}-jungle2-fix',
    '-f', 'Dockerfile-eos-prod',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-eos-full:${_TAG}-jungle2-fix
- gcr.io/$PROJECT_ID/eosio-eos-full:${_TAG}-${SHORT_SHA}-jungle2-fix
- gcr.io/$PROJECT_ID/eosio-eos-prod:${_TAG}-${SHORT_SHA}-jungle2-fix

timeout: 1h
