steps:

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/eoscanada-shared-services/eosio-nodeos-full:$_DSTTAG',
    '-f', 'Dockerfile-nodeos-full',
    '--build-arg', 'SRCTAG=$_SRCTAG',
    '--build-arg', 'BUILD_ENV=v7',
    '--build-arg', 'PATCHES=$_PATCHES',
    '.'
  ]

images:
- gcr.io/eoscanada-shared-services/eosio-nodeos-full:$_DSTTAG
