### commit and push those values in !
substitutions:
  _TAG: v1.6.2
    # check appropriate builder tag in https://hub.docker.com/r/eosio/builder/tags
  _BUILDER_TAG: v1.5.2
  _PATCHES: "deep-mind-v1.6.2-v9.1.patch deep-mind-logging-v1.6.2-v9.1.patch"

steps:
- id: docker-build-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind',
    '-f', 'Dockerfile-nodeos-full',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'BLDTAG=${_BUILDER_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]

- id: deep-mind-tests
  name: gcr.io/${PROJECT_ID}/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}
  dir: /workspace/deep-mind/compare
  env:
  - "SKIP_GO_TESTS=y"
  args: [
    './run.sh', '/opt/eos/bin/nodeos'
  ]

# Download SSH encrypted private key and SSH known hosts file
- id: download-ssh-encrypted-private-key
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/github_id_rsa.enc', '/root/.ssh/github_id_rsa.enc']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: download-ssh-known-hosts-file
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/github_known_hosts', '/root/.ssh/known_hosts']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Decrypting SSH encrypted private key
- id: decrypt-ssh-encrypted-private-key
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --project=eoscanada-public
  - --ciphertext-file=/root/.ssh/github_id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=github-keys
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Initializing Git with SSH credentials and URL transformation
- id: configure-git-for-private-repositories-access
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    git config --global --add url."git@github.com:".insteadOf "https://github.com/"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git'
    path: /root/.git

# Perform the actual build/test step of the project
- id: deep-mind-go-tests
  name: gcr.io/cloud-builders/go:debian
  entrypoint: 'sh'
  env:
  - CGO_ENABLED=0
  args:
  - '-cxe'
  - |
    cd /workspace/deep-mind/compare
    go test -v ./...
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git'
    path: /root/.git

- id: docker-build-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-prod:${_TAG}-deep-mind-${SHORT_SHA}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-nodeos-prod:${_TAG}-deep-mind',
    '--build-arg', 'NODEOS_FULL_TAG=${_TAG}-deep-mind-${SHORT_SHA}',
    '-f', 'Dockerfile-nodeos-prod',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-nodeos-full:${_TAG}-deep-mind
- gcr.io/$PROJECT_ID/eosio-nodeos-full:${_TAG}-deep-mind-${SHORT_SHA}
- gcr.io/$PROJECT_ID/eosio-nodeos-prod:${_TAG}-deep-mind-${SHORT_SHA}

