### commit and push those values in !
substitutions:
  _TAG: v1.8.1
  # Check available tags via `gcr.io/${PROJECT_ID}/eosio-buildenv` images
  _EOSIO_BUILDENV_TAG: v1.8.0-rc2

steps:
- id: docker-eos-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}-${SHORT_SHA}',
    '-f', 'Dockerfile-eos-full',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-eos-full:${_TAG}',
    '--build-arg', 'EOSIO_BUILDENV_TAG=${_EOSIO_BUILDENV_TAG}',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]
- id: docker-eos-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-prod:${_TAG}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-eos-prod:${_TAG}-${SHORT_SHA}',
    '--build-arg', 'EOS_FULL_TAG=${_TAG}-${SHORT_SHA}',
    '-f', 'Dockerfile-eos-prod',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-eos-full:${_TAG}
- gcr.io/$PROJECT_ID/eosio-eos-full:${_TAG}-${SHORT_SHA}
- gcr.io/$PROJECT_ID/eosio-eos-prod:${_TAG}-${SHORT_SHA}

timeout: 1h
