steps:

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/eosio-nodeos-prod:$COMMIT_SHA',
    '-f', 'Dockerfile-nodeos-prod',
    '--build-arg', 'BRANCH=$COMMIT_SHA',
    '.'
  ]

- id: push-dockerfile
  name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'Dockerfile-nodeos-prod', 'gs://artifacts.eoscanada-public.appspot.com/metadata/eosio-nodeos-prod/$COMMIT_SHA/Dockerfile']

images:
- gcr.io/$PROJECT_ID/eosio-nodeos-prod:$COMMIT_SHA
