steps:

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/eosio-nodeos-full:$_DSTTAG',
    '-f', 'Dockerfile-nodeos-full',
    '--build-arg', 'SRCTAG=$_SRCTAG',
    '--build-arg', 'BUILD_ENV=v7',
    '--build-arg', 'PATCHES=$_PATCHES',
    '.'
  ]

#- id: deep-mind-tests
#  name: gcr.io/cloud-builders/docker
#  args: [
#    'run', '-ti', '--rm', '-v', '`pwd`:/workspace',
#    'gcr.io/$PROJECT_ID/eosio-nodeos-full:$_DSTTAG',
#    '/workspace/deep-mind/run_tests.sh'
#  ]

- id: push-dockerfile
  name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'Dockerfile-nodeos-full', 'gs://artifacts.eoscanada-public.appspot.com/metadata/eosio-nodeos-full/$_DSTTAG/Dockerfile']

images:
- gcr.io/$PROJECT_ID/eosio-nodeos-full:$_DSTTAG
