### commit and push those values in !
substitutions:
  _REPOSITORY: "git@github.com:dfuse-io/eos.git"
  _IMAGE_TAG: ubuntu-18.04
  _BRANCH: v2.0.12-dm-12.0 # Can be either a tag or a branch, branch can be used when "testing" stuff out

steps:
# Download SSH encrypted private key and SSH known hosts file
- id: download-ssh-files
  name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    gsutil cp gs://${PROJECT_ID}_cloudbuild/github_id_rsa.enc /root/.ssh/github_id_rsa.enc
    gsutil cp gs://${PROJECT_ID}_cloudbuild/github_known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- id: download-ssh-known-hosts-file
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://${PROJECT_ID}_cloudbuild/github_known_hosts', '/root/.ssh/known_hosts']
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Decrypting SSH encrypted private key
- id: decrypt-ssh-encrypted-private-key
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --project=eoscanada-public
  - --ciphertext-file=/root/.ssh/github_id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=github-keys
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Initializing Git with SSH credentials and URL transformation
- id: configure-git-for-private-repositories-access
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
    EOF

    git config --global --add url."git@github.com:dfuse-io/".insteadOf "https://github.com/dfuse-io/"
    git config --global --add url."git@github.com:eoscanada/".insteadOf "https://github.com/eoscanada/"

    # Use our own fork of ultra-fc for now since CloubBuild credentials doesn't have access to this ...
    git config --global --add url."git@github.com:dfuse-io/eosio-fc-private".insteadOf "git@github.com:ultraio/ultra-fc"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git_home'
    path: /root/.git

- id: clone-source
  name: gcr.io/cloud-builders/git
  args: [
    'clone',
    '--branch=${_BRANCH}',
    '--depth=1',
    '--recursive',
    '${_REPOSITORY}',
    '/git',
  ]
  volumes:
  - name: 'git'
    path: '/git'
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git_home'
    path: /root/.git

- id: docker-image
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
  - PLATFORM_TYPE=pinned
  - IMAGE_TAG=${_IMAGE_TAG}-pinned
  - FORCE_BASE_IMAGE=true
  # Supports for both <= 2.0.7 and >= 2.0.8
  - IMAGE_NAME=gcr.io/${PROJECT_ID}/eosio-ci        # Used by <= 2.0.7
  - MIRROR_REGISTRY=gcr.io/${PROJECT_ID}/eosio-ci   # Used by >= 2.0.8
  args:
  - '-cxe'
  - |
    env

    cd /git
    ./.cicd/generate-base-images.sh

    . .cicd/helpers/file-hash.sh .cicd/platforms/$$PLATFORM_TYPE/$$IMAGE_TAG.dockerfile
    docker tag $$FULL_TAG gcr.io/${PROJECT_ID}/eosio-ci:${_IMAGE_TAG}-latest

    # We push the full tag image right away otherwise the tag is lost
    docker push $$FULL_TAG
  volumes:
  - name: 'git'
    path: '/git'

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/${PROJECT_ID}/eosio-ci:${_IMAGE_TAG}-latest

timeout: 1h
