### Commit and push those values in!
substitutions:
  _REPOSITORY: "git@github.com:dfuse-io/eosio-eos-private.git"
  _BRANCH: release/ultra/2.0.x-dm # Can be either a tag or a branch, branch can be used when "testing" stuff out
  _VERSION: v2.0.7-1.1.0-dm.12.0
  _IMAGE_TAG: ubuntu-18.04
  _OS: ubuntu-18.04
  _PKGTYPE: deb

steps:
# Download SSH encrypted private key and SSH known hosts file
- id: download-ssh-files
  name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    gsutil cp gs://${PROJECT_ID}_cloudbuild/github_id_rsa.enc /root/.ssh/github_id_rsa.enc
    gsutil cp gs://${PROJECT_ID}_cloudbuild/github_known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Decrypting SSH encrypted private key
- id: decrypt-ssh-encrypted-private-key
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --project=eoscanada-public
  - --ciphertext-file=/root/.ssh/github_id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=github-keys
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Initializing Git with SSH credentials and URL transformation
- id: configure-git-for-private-repositories-access
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-ce'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
    EOF

    git config --global --add url."git@github.com:dfuse-io/".insteadOf "https://github.com/dfuse-io/"
    git config --global --add url."git@github.com:eoscanada/".insteadOf "https://github.com/eoscanada/"

    # Use our own fork of ultra-fc for now since CloubBuild credentials doesn't have access to this ...
    git config --global --add url."git@github.com:dfuse-io/eosio-fc-private".insteadOf "git@github.com:ultraio/ultra-fc"
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git_home'
    path: /root/.git

- id: cloning source code
  name: gcr.io/cloud-builders/git
  args: [
    'clone',
    '--branch=${_BRANCH}',
    #    '--depth=1', # this prevents the 'describe' command from finding the tag
    '--recursive',
    '${_REPOSITORY}',
    '/git',
  ]
  volumes:
  - name: 'git'
    path: '/git'
  - name: 'ssh'
    path: /root/.ssh
  - name: 'git_home'
    path: /root/.git

- id: building source code
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
  # The ARGS is used for `docker run <ARGS>` part, and in CloudBuild, the source mount volume must be the volume name not the path! See `volumes`
  # FIXME: Building 2.0.8 will require to update `ARGS=--rm --init -v git:/workdir` to `ARGS=--rm --init -v git:/eos`
  - ARGS=--rm --init -v git:/workdir
  - PLATFORM_TYPE=pinned
  - IMAGE_TAG=${_IMAGE_TAG}-pinned
  # Supports for both <= 2.0.7 and >= 2.0.8
  - IMAGE_NAME=gcr.io/${PROJECT_ID}/eosio-ci        # Used by <= 2.0.7
  - MIRROR_REGISTRY=gcr.io/${PROJECT_ID}/eosio-ci   # Used by >= 2.0.8
  args:
  - '-cxe'
  - |
    env

    cd /git
    ./.cicd/build.sh
  volumes:
  - name: 'git'
    path: '/git'

- id: extract librdkafka.so libraries
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
  # FIXME: Building 2.0.8 will require to update `ARGS=--rm --init -v git:/workdir` to `ARGS=--rm --init -v git:/eos`
  - ARGS=--rm --init -v git:/workdir
  - PLATFORM_TYPE=pinned
  - IMAGE_TAG=${_IMAGE_TAG}-pinned
  - OS=${_OS}
  - PKGTYPE=${_PKGTYPE}
  # Supports for both <= 2.0.7 and >= 2.0.8
  - IMAGE_NAME=gcr.io/${PROJECT_ID}/eosio-ci        # Used by <= 2.0.7
  - MIRROR_REGISTRY=gcr.io/${PROJECT_ID}/eosio-ci   # Used by >= 2.0.8
  args:
  - '-cxe'
  - |
    env

    cd /git
    . .cicd/helpers/file-hash.sh .cicd/platforms/$$PLATFORM_TYPE/$$IMAGE_TAG.dockerfile

    # The source mount volume must be the volume name not the path!
    docker run --rm --init -v git:/workdir $$FULL_TAG cp /usr/local/lib/librdkafka.so.1 /workdir/build/packages
  volumes:
  - name: 'git'
    path: '/git'

- id: package distribution
  name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  env:
  # The ARGS is used for `docker run <ARGS>` part, and in CloudBuild, the source mount volume must be the volume name not the path! See `volumes`
  # FIXME: Building 2.0.8 will require to update `ARGS=--rm --init -v git:/workdir` to `ARGS=--rm --init -v git:/eos`
  - ARGS=--rm --init -v git:/workdir
  - PLATFORM_TYPE=pinned
  - IMAGE_TAG=${_IMAGE_TAG}-pinned
  - OS=${_OS}
  - PKGTYPE=${_PKGTYPE}
  # Supports for both <= 2.0.7 and >= 2.0.8
  - IMAGE_NAME=gcr.io/${PROJECT_ID}/eosio-ci        # Used by <= 2.0.7
  - MIRROR_REGISTRY=gcr.io/${PROJECT_ID}/eosio-ci   # Used by >= 2.0.8
  args:
  - '-cxe'
  - |
    env

    cd /git
    ./.cicd/package.sh
  volumes:
  - name: 'git'
    path: '/git'

##
# Those are steps that leverage the `.devops` folder of Ultra repository to build the release. Since our old env
# was able to actually to build when tweaked to only build `nodeos` and `cleos`, we prefer to use those for now.
# Left the steps in there in case we are required to change in the future.
#
# - id: building source code
#   name: gcr.io/${PROJECT_ID}/ultra-ci:${_IMAGE_TAG}-latest
#   entrypoint: 'bash'
#   args:
#   - '-cxe'
#   - |
#     env

#     cd /git

#     # Remove check of minimal resource during build (7GB RAM and 5GB disk)
#     cp -p .devops/eosio_build_ubuntu.sh scripts/
#     chmod +x ./scripts/eosio_build_ubuntu.sh ./scripts/eosio_build.sh ./scripts/eosio_install.sh

#     ./scripts/eosio_build.sh -o Release -s UOS -m -y -P
#   volumes:
#   - name: 'git'
#     path: '/git'

# - id: package distribution
#   name: gcr.io/${PROJECT_ID}/ultra-ci:${_IMAGE_TAG}-latest
#   entrypoint: 'bash'
#   args:
#   - '-cxe'
#   - |
#     env

#     cd /git

#     cp -p .devops/generate_package.sh .devops/generate_deb.sh build/packages/
#     cd ./build/packages
#     chmod +x ./generate_package.sh ./generate_deb.sh
#     ./generate_package.sh deb
#   volumes:
#   - name: 'git'
#     path: '/git'

- id: docker-build-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}',
    '-f', 'ultra-${_IMAGE_TAG}.dockerfile',
    '--build-arg', 'VERSION=${_VERSION}',
    '/git/build/packages'
  ]
  volumes:
  - name: 'git'
    path: '/git'

- id: docker-tag-untested
  name: gcr.io/cloud-builders/docker
  args: [
    'tag',
    'gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}',
    'gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}-untested',
  ]
  volumes:
  - name: 'git'
    path: '/git'

- id: docker-push-untested
  name: gcr.io/cloud-builders/docker
  args: [
    'push',
    'gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}-untested',
  ]
  volumes:
  - name: 'git'
    path: '/git'

# Perform the actual build/test step of the project
# - id: deep-mind-nodeos-tests
#   name: gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}
#   entrypoint: bash
#   args:
#   - '-cxe'
#   - |
#     if [[ "${_VERSION}" =~ "dm" ]]; then
#       cd /workspace/deep-mind/compare
#       SKIP_GO_TESTS=y ./run.sh ultra-2.x /usr/bin/nodeos
#     fi

# - id: deep-mind-go-tests
#   name: gcr.io/cloud-builders/go:debian
#   entrypoint: 'bash'
#   env:
#   - CGO_ENABLED=1
#   - GOPRIVATE=github.com/eoscanada/*,github.com/dfuse-io/*
#   args:
#   - '-cxe'
#   - |
#     if [[ "${_VERSION}" =~ "dm" ]]; then
#       cd /workspace/deep-mind/compare
#       TARGET=ultra-2.x go test -v ./...
#     fi
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh
#   - name: 'git_home'
#     path: /root/.git

- id: package copy to bucket
  name: gcr.io/cloud-builders/gsutil
  args: [
    'cp',
    '/git/build/packages/*.${_PKGTYPE}',
    'gs://eoscanada-shared-services_cloudbuild/packages/ultra/${_OS}/',
  ]
  volumes:
  - name: 'git'
    path: '/git'

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-ultra-prod:${_VERSION}-${_OS}

timeout: 1h
