### commit and push those values in !
substitutions:
  _TAG: wax-1.8.4-1.0.0
  # Check available images with `gcloud container images list-tags gcr.io/eoscanada-shared-services/eosio-buildenv`
  _EOSIO_BUILDENV_TAG: v1.8.1

steps:
- id: docker-eos-full
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-wax-full:${_TAG}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-wax-full:${_TAG}-${SHORT_SHA}',
    '-f', 'wax-full.dockerfile',
    '--cache-from', 'gcr.io/${PROJECT_ID}/eosio-wax-full:${_TAG}',
    '--build-arg', 'EOSIO_BUILDENV_TAG=${_EOSIO_BUILDENV_TAG}',
    '--build-arg', 'SRCTAG=${_TAG}',
    '--build-arg', 'PATCHES=${_PATCHES}',
    '.'
  ]
- id: docker-eos-prod
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-wax-prod:${_TAG}',
    '-t', 'gcr.io/${PROJECT_ID}/eosio-wax-prod:${_TAG}-${SHORT_SHA}',
    '--build-arg', 'EOS_FULL_TAG=${_TAG}-${SHORT_SHA}',
    '-f', 'wax-prod.dockerfile',
    '.'
  ]

options:
  machineType: 'N1_HIGHCPU_32'

images:
- gcr.io/$PROJECT_ID/eosio-wax-full:${_TAG}
- gcr.io/$PROJECT_ID/eosio-wax-full:${_TAG}-${SHORT_SHA}
- gcr.io/$PROJECT_ID/eosio-wax-prod:${_TAG}-${SHORT_SHA}

timeout: 1h
